### PR TITLE
Remove strings.ReplaceAll for Go 1.11 compatibility

### LINKED ISSUE #37: Build error on go 1.11
Getting the below error while building yunikorn-core on go 1.11.

```
../yunikorn-core/pkg/scheduler/placement/rule.go:112:9: undefined: strings.ReplaceAll
note: module requires Go 1.12
make: *** [build_image] Error 2
```

Looks like strings.ReplaceAll is only available in Go 1.12 .  The docs mention go 1.11+ can be used. So we can either,
* Change the doc to mention only Go 1.12+
(or)
* Change ReplaceAll to Replace to make it work in go 1.11 .

```
-       return strings.ReplaceAll(name, cache.DOT, cache.DotReplace)
+       return strings.Replace(name, cache.DOT, cache.DotReplace, -1)
```

### PR DESCRIPTION
**Pull request by wilfred-s**
Replace the new strings.ReplaceAll() method call with the old strings.Replace() call.

ReplaceAll was introduced in G0 1.12 as most of the calls use a -1 anyway.

Closes #37

### CODE REVIEW

**Comment by yangwwei** [comment]
this resolves #37
