### ISSUE TITLE
Build error on go 1.11

### ISSUE THREAD

**Issue by TarunParimi** [cloudera/yunikorn-core#37]
Getting the below error while building yunikorn-core on go 1.11.

```
../yunikorn-core/pkg/scheduler/placement/rule.go:112:9: undefined: strings.ReplaceAll
note: module requires Go 1.12
make: *** [build_image] Error 2
```

Looks like strings.ReplaceAll is only available in Go 1.12 .  The docs mention go 1.11+ can be used. So we can either,
* Change the doc to mention only Go 1.12+
(or)
* Change ReplaceAll to Replace to make it work in go 1.11 .

```
-       return strings.ReplaceAll(name, cache.DOT, cache.DotReplace)
+       return strings.Replace(name, cache.DOT, cache.DotReplace, -1)
```

**Comment by yangwwei** [comment]
Go 1.11 was released at Aug 24, 2018, not a long time ago, we'd better to support.
I prefer the 2nd option, @wilfred-s what do you think?

**Comment by wilfred-s** [comment]
PR opened to fix this.
